# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.15"
  i386: "ghcr.io/home-assistant/i386-base-python:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MTECmqtt"
  org.opencontainers.image.description: "MTECmqtt add-on for Home Assistant."
  org.opencontainers.image.source: "https://github.com/codehasi/home-assistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
