# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MTECmqtt Home Assistant add-on
version: "1.0.0"
slug: mtecmqtt
description: Home Assistant add-on for MTECmqtt
url: "https://github.com/codehasi/home-assistant-addons/tree/main/mtecmqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
schema:
  message: "str?"
image: "ghcr.io/codehasi/{arch}-addon-MTECmqtt"
startup: services

